### ISSUE TITLE
Should it be allowed to create range from single address?

### ISSUE THREAD

**Issue by OlegAndreych** [maltalex/ineter#1]
I think it should be allowed to create an IPv4Range and IPv6Range from a single address like:
```java
IPv6Range.of("1::")
IPv4Range.between("127.0.0.1")
```
I want it to be allowed because sometimes single address is a special case of a range and it's convenient to have uniform processing of all the data you have.

**Comment by maltalex** [comment]
So you'd like to see something like `IPv4Range.between("127.0.0.1")` produce the same result as `IPv4Range.between("127.0.0.1-127.0.0.1")`?

I find it a bit odd calling this function `between` despite the user supplying it a single address, but I see your point. Perhaps we need a different name for a function that can accept a String range like `1.2.3.4-4.3.2.1` AND a single IP address?

**Comment by OlegAndreych** [comment]
What about `from` then?

**Comment by maltalex** [comment]
How about we call it `parse` and make it work with CIDR-style subnets too?

This way one could write `IPv4Range.parse("1.2.3.0/24")` and get an IPv4Range which is in fact an IPv4Subnet instance.

**Comment by OlegAndreych** [comment]
`parse` sounds good for me either.

Well, if we're talking about subnets, should we make them accept single address too? E.g. it would be `/32` subnet for IPv4 or `/128` for IPv6.

**Comment by maltalex** [comment]
You mean we add a `parse` method for `IPv4Subnet` and `IPv6Subnet` that can take single addresses? That sounds reasonable.

**Comment by OlegAndreych** [comment]
Ok, I'll add it then.

**Comment by maltalex** [comment]
Are you planning to implement the subnet parsing too?

Also, please don't delete `between`. Instead deprecate it for now. This way, we don't break anything for v0.1.1

**Comment by OlegAndreych** [comment]
Yes, I'm planning to implement subnet parsing.
Should we delegate `between` to `parse`, or restore original behaviour (fail on single address)?

**Comment by maltalex** [comment]
nah, keep the current implementation for now. It's just a few lines anyway.
We'll delete it in the next version.

**Comment by OlegAndreych** [comment]
Well, I suppose it's done for now. I've tried to unify parsing of ranges and subnets between IPv4 and IPv6 because they're quite similar. The only obstacle I've met is different types for mask length (byte, int).
