### ISSUE TITLE
Merge method for ranges

### ISSUE THREAD

**Issue by OlegAndreych** [maltalex/ineter#3]
As for now, everything can be converted to a range, I think it's a good idea to add static `merge` method to `IPvXRange` classes so we can merge adjacent addresses and ranges to bigger ones.

**Comment by maltalex** [comment]
Sounds good. We could also add a regular (not static) method called `extend` that accepts an adjacent range (or a single adjacent IP) and would return a new `IPvXRange`.

**Comment by OlegAndreych** [comment]
Let's code then!
I already have an implementation for IPv4, so I plan to port it soon and adapt it for the aforementioned cases.

**Comment by maltalex** [comment]
What do you plan on returning in cases when the ranges aren't adjacent?

**Comment by OlegAndreych** [comment]
In case, when the static method is in use, return a collection with all of the ranges from args (nothing merged).
In the case of an instance method, all of the ranges from args + `this`.
So there's a consistency and instance method is a mere delegate to static one.

**Comment by maltalex** [comment]
So you want to return a collection? I thought you wanted to return a single, bigger range. 

Could you maybe share the code you have so far so we're on the same page?

**Comment by OlegAndreych** [comment]
Yes, I want to return a collection. If all the ranges can be merged there will be a collection with only one uber-range.

Well, I'm struggling to make a merging algorithm generic for all the IPvXAddress implementations mostly because `IPAddress` is not `Comparable`, but `IPRange`'s `T` generic type is, and every `IPAddress` implementation implements (>_<) this interface.
Changing this now is a bad idea in my opinion, but I have a couple of solutions in my mind, so eventually, I can come up with proper `merge` implementations.

In the meantime, you can see an example of what I'm trying to achieve (more or less) here https://github.com/OlegAndreych/rknlistuploader/blob/master/src/main/java/ru/andreych/rkn/list/uploader/range/IPRangesMerger.java

**Comment by maltalex** [comment]
First of all, like I've written in the past - don't worry too much about creating generic code. We're not likely to have IPv7 anytime soon. Having two similar implementations might not feel "clean", but _if it's stupid and it works, it's not stupid_. Also, overly generic code is often less readable and sometimes less performant.

Second, yes. The current API has some design issues. I ran into some of them too while considering IP address collections. I even had some initial implementations of an  `ImmutableIpAddressSet` laying around somewhere, which sounds a bit like what you're after.

As much as I hate breaking compatibility, I'll probably do it at some point soon and release a non-compatible 0.2.0 version with several breaking changes to streamline the API. I'll try to find some time to work on it soon.

Of course you could still contribute code to the 0.1.x line.

**Comment by OlegAndreych** [comment]
In case I'll not find any fruitful solution in the nearest future, I'll resort to your advise. Chunk of code I have for merging is significantly bigger than one we had at hands, when we have this conversation in past. So I decided to make it "proper" way first.

**Comment by maltalex** [comment]
Take a look at the `v0.2.x-dev` branch.  I pushed a version with some of the changes I wanted to make in 0.2.

**Comment by OlegAndreych** [comment]
Looks great.
Shouldn't `IPAddress` be `Comparable` by itself?
More feedback may come during porting of this issue to the new branch.

**Comment by maltalex** [comment]
The problem with making IPAddress itself comparable is that it allows for comparisons between IPv4 and IPv6 addresses which is nonsensical. What’s bigger 1.2.3.4 or 1:2:3:4::?

**Comment by OlegAndreych** [comment]
Ability to compare between IPv4 and IPv6 depends on implementation.
As a workaround, we can have a generic type parameter `IPAddress<C extends IPAddress>`. In child classes we have a type argument `public class IPv4Address extends IPAddress<IPv4Address> ` just like we have one for `Comparable<IPv4Address>`.
I've implemented this technique in `isAdjacentTo` method for the exact same reason, as you described.
Although you can not compare IPv6 with IPv4 address, addresses by themselves are comparable (I don't have any counterexample), so that is the reason for my proposal.

**Comment by OlegAndreych** [comment]
I hope I didn't make you upset with any of my actions.

**Comment by maltalex** [comment]
> Ability to compare between IPv4 and IPv6 depends on implementation.

Of course. I was just saying that the comparison of IPv4 and IPv6 is meaningless by definition regardless of implementation.

> As a workaround, we can have a generic type parameter IPAddress<C extends IPAddress>. In child classes we have a type argument public class IPv4Address extends IPAddress<IPv4Address> just like we have one for Comparable<IPv4Address>.

It took me a while to understand what you mean. I only got it after glancing at your commits (haven't had to read them thoroughly yet). It's a bit weird - I mean, it's an interface with a generic argument of itself.... But nevertheless it solves the problem at hand, and is applicable to other methods that need to accept or return an IPAddress of the same type. So I like it.

> I hope I didn't make you upset with any of my actions.

What gave you that idea? You haven't upset me in any way. We're having a technical discussion. We can sometimes disagree, but that's fine, no worries. It's good to have another pair of eyes on the code.

**Comment by OlegAndreych** [comment]
If we came to an agreement on this, I'll wait for the review to complete and if everything will be considered fine, I'll port changes to 0.2.

**Comment by maltalex** [comment]
I gave it some more thought, and I've started to dislike the `IPAddress<C extends IPAddress>` idea. The problem is that it would force users to use the generic form `IPAddress<?>` when referencing addresses which might be either IPv6 or IPv4. So this: `IPAddress foo = ...` would have to become `IPAddress<?> foo =... ` in user code, which is ugly. It's even uglier in case of collections: `List<IPAddress<?>>`.

Since `ineter` is a library, it's more important to have a clean external API, than a cleaner/more generic internal implementation. So unless we come up with a different generic solution, I prefer to just have two separate implementations in this case. Like I've already said, IPv7 isn't going to appear anytime soon.

btw, I would have happily removed the generic types from the other interfaces too (IPRange and IPSubnet), but they're there not just to have a more minimal implementation. Rather, they're there because almost all functions declared by these interfaces require the generic type(s).

**Comment by OlegAndreych** [comment]
As I can see we have several options:
1. Use generics and leave a user with ugly `<?>`;
2. Don't use generics, but declare methods like `compareTo` on the `IPAddress` level, which leads us to not typesafe code, but it's like standard library works sometimes (`clone`, `get`'s argument on a `Map`);
3. Declare some methods only in concrete types forcing a user to do `instanceof` checks with casts;

I still think that e.g. `IPAddress` should be `Comparable` because all implementations are comparable just not between classes. I still think that typesafe variant with `<?>` is better than the unsafe one. `<?>` may be ugly, but this is how you can guarantee typesafety beyond runtime `instanceof` checks and this is how most of the generic java code works. Yes, sometimes you're not interested in what exact type you have IPv4 or IPv6, but you may want to be sure, that in all cases it's the same type. That's where even `<?>` become useful. If it's not the case and a user understands all the implications, it can consider resorting to raw types anyway and ugly generic argument will be gone for good. Last but not least, in many cases, you don't have to bother with long types, as we'll have an empty diamond `<>`.
As a second variant would I prefer untyped one, and as the last one - methods in children.

All that was said by me as a user of this library, not as a developer (despite it can be useful in the internal parts).

**Comment by maltalex** [comment]
Let's backtrack a bit. What use case do you see for making `IPAddress` comparable?

I ran into just one - writing generic code that can handle both IPv4 and IPv6. For example, a custom collection that can handle both types of addresses. I have a draft of such a collection which I haven't published (yet). In that collection I simply implemented the generic logic in a top level abstract class e.g. `AbstractIPAddressCollection`, which had two extending classes - `IPv4AddressCollection` and `IPv6AddressesCollection`. 

Why am I telling you this? Well, for comparisons, the abstract class has a `abstract Comparator<T> getFirstAddressComparator()` method (or something similar). The extending classes implement that method, providing a type-safe comparator for the generic code in the abstract class to use. This approach is type safe and avoids code duplication. 

What use case(s) did you ran into?

**Comment by maltalex** [comment]
Hmm... I just had an idea for an _over-engineered_ option number 4. We can use **two** interfaces.

`IPAddress` will remain the top level interface that will define the basic methods _all_ IP addresses have. Extending it, we'll have something like a `public interface ExtendedIPAddress<C extends IPAddress> extends IPAddress`. 

That extended interface (which will be implemented by the concrete classes of course) will add methods such as your `isAdjacentTo` which takes the generic `C` as an argument. This way users will be able to keep using the non-generic `IPAddress`, with the same methods it has now. But internally, ineter (and other users who wish to write custom generic code around ineter) will be able to use the extended interface if they need the generic methods like `compareTo`.

This way `IPAddress` remains plain and simple, without annoying generics. And we keep our precious type safety :)

**Comment by OlegAndreych** [comment]
If you see this as a more pleasing option I have not a single objection. Let's move this way.

**Comment by maltalex** [comment]
Agreed. Then please update #4.

**Comment by OlegAndreych** [comment]
Do you plan to maintain 0.1 after 0.2 being released?
If not, given the number of changes after discussion, I'd prefer to make changes on this issue in  0.2 only.

**Comment by maltalex** [comment]
I'm fine with making the merge feature on 0.2 only.

At the moment #4 changes `public abstract class IPAddress` to `public abstract class IPAddress<C extends IPAddress>`

**Comment by OlegAndreych** [comment]
Please check #6. Is that what you wanted?
