### ISSUE TITLE
RFC Compliance

### ISSUE THREAD

**Issue by hyperxpro** [maltalex/ineter#8]
Is this library compliant with the RFC of IPv4 and IPv6?

**Comment by maltalex** [comment]
Hi @hyperxpro 

It hasn't been written specifically against the relevant RFCs (except in some specific areas here and there), so there are no guarantees.

However, I'm not aware of any specific contradictions between the spec and the ineter implementation. Is there anything specific you're worried about? The code is fairly straightforward and documented, so you can always check for yourself.

**Comment by hyperxpro** [comment]
We were planning to use this library in our main production system so thought it's better to ask before integrating and deploying. I will have a look at source code and let you know if I need some help. 

This library is way faster and efficient from other libraries for IP Addresses in Java so we choose this. Thanks a lot for your hard work on this!

**Comment by maltalex** [comment]
Thank you. I hope you find the library useful

**Comment by maltalex** [comment]
Thank you.
I'm happy to hear that you found the library useful.
