### ISSUE TITLE
Support for IP exclusion??

### ISSUE THREAD

**Issue by suhail-sullad** [maltalex/ineter#9]
It would be nice to have an IP exclusion function in IPRange.

Say for example:
i have a range of 1.1.1.1-1.1.1.8 and i want to exclude 1.1.1.2-1.1.1.5
so the resultant range should be 1.1.1.1-1.1.1.1,1.1.1.6-1.1.1.8

**Comment by maltalex** [comment]
So something like a `myRange.exclude(someOtherRange)` that returns a pair (or list?) of two elements?

**Comment by suhail-sullad** [comment]
Yes. It would remove the excluded range or IP or CIDR and generate a new range or IP. 
Probably a list would be better.

**Comment by maltalex** [comment]
Sure, that's a good idea, I'll implement it when I have some free time.

**Comment by reutsharabani** [comment]
@maltalex I think you solved this by merging https://github.com/maltalex/ineter/pull/12

**Comment by maltalex** [comment]
Released in v0.3.0
